name: Compile SCSS to CSS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile-scss:
    name: Compile SCSS
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Instalar Sass
      - name: Install Sass
        run: |
          npm install -g sass

      # 4. Compilar SCSS a CSS
      - name: Compile SCSS
        run: |
          sass styles.scss:style.css

      # 5. Subir los cambios de CSS al repositorio
      - name: Commit and Push CSS
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-compiled SCSS to CSS"
          file_pattern: style.css
